artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.dropbox.com/scl/fi/gkx3j9gk3eg45c2mjyf1s/data_doc_classify.zip?rlkey=mw2iuc5ha4bzy5u3hx0unr603&dl=0
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["balance sheet", "cashflow", "income statement"]
  unzip_dir: artifacts/data_ingestion/data

data_preparation:
  root_dir: artifacts/data_preparation
  STATUS_FILE: artifacts/data_preparation/status.txt  
  unzip_dir: artifacts/data_ingestion/data

data_training_validation:
  root_dir: artifacts/data_training_validation
  STATUS_FILE: artifacts/data_training_validation/status.txt  
  unzip_dir: artifacts/data_ingestion/data  

  
